Checkmarx/ast-jetbrains-plugin

.github/workflows/ast-scan.yml, .github/workflows/ci.yml
Split AST scan into a new file
=> Split ast scan into a new file

.github/workflows/ast-scan.yml
=> add sca resolver

.github/workflows/ast-scan.yml
- Remove SCA resolver 
- Add include in scan gradle and gradlew files
=> Remove SCA resolver

src/main/java/com/checkmarx/intellij/tool/window/results/tree/nodes/ResultNode.java
Fix ordering of comment field in triage form
N/A
N/A
=> fix comment field ordering

src/main/java/com/checkmarx/intellij/tool/window/results/tree/nodes/ResultNode.java
Fix for Additional Knowledge errors on empty link
https://checkmarx.atlassian.net/browse/AST-18184?atlOrigin=eyJpIjoiMjkwMWE5MGMxYzczNDc0MjhjZTNlNGM2MGNjZTJjOTciLCJwIjoiaiJ9
=> SCA - Fix for Additional Knowledge errors on empty link

build.gradle, src/main/java/com/checkmarx/intellij/tool/window/actions/CancelScanAction.java, src/main/java/com/checkmarx/intellij/tool/window/actions/StartScanAction.java
Avoid calling CLI commands on Action constructors
N/A
N/A
=> Avoid calling CLI commands on Action constructors

.github/workflows/release.yml, build.gradle
DEV-RELEASE
- pre-release option and optional publish plugin channel
- setting java wrapper version
https://checkmarx.atlassian.net/browse/AST-24012?atlOrigin=eyJpIjoiMzNiZmUwY2MyY2JlNDFkYzg3ZjY0YjAzMTIyMTY3MjQiLCJwIjoiaiJ9
>
> Please include any manual steps for testing end-to-end or …
=> DEV release support

.github/workflows/nightly.yml, build.gradle
https://checkmarx.atlassian.net/browse/AST-24016?atlOrigin=eyJpIjoiNjgwZWZmMzM0YWU0NGIwMDhkNWMwODQ2Mzk2N2E5OGMiLCJwIjoiaiJ9
=> DEV-RELEASE - testing nightly

.github/workflows/release.yml, build.gradle
https://checkmarx.atlassian.net/browse/AST-24016?atlOrigin=eyJpIjoiNjgwZWZmMzM0YWU0NGIwMDhkNWMwODQ2Mzk2N2E5OGMiLCJwIjoiaiJ9
=> Fix for publishPlugin property

.github/workflows/delete-dev-releases.yml, .github/workflows/nightly.yml, .github/workflows/release.yml
References
https://checkmarx.atlassian.net/browse/AST-24016?atlOrigin=eyJpIjoiNjgwZWZmMzM0YWU0NGIwMDhkNWMwODQ2Mzk2N2E5OGMiLCJwIjoiaiJ9
=> Renaming developer builds tag with timestamp pattern

src/main/java/com/checkmarx/intellij/tool/window/actions/StartScanAction.java
- Remove unused import
> Don't warn user if there is no results in scan id
> Remove unused import
>
=> Change mismatch warning behavior

.github/workflows/ci.yml, build.gradle, src/main/java/com/checkmarx/intellij/Utils.java, src/test/java/com/checkmarx/intellij/ui/BaseUITest.java, src/test/java/com/checkmarx/intellij/ui/TestGeneral.java, src/test/java/com/checkmarx/intellij/ui/TestSca.java
Fix UI tests 
https://checkmarx.atlassian.net/browse/AST-37917 
Run test locally
=> JetBrains | Fix UI Tests

build.gradle
Upgrade Java Wrapper version
https://checkmarx.atlassian.net/browse/AST-41951
>
=> JetBrains | Upgrade Java Wrapper version (AST-41951)

src/main/resources/META-INF/plugin.xml
Rename the plugin to "Checkmarx One" to distinguish it from the SAST plugin
https://checkmarx.atlassian.net/browse/AST-34937
Do not need
=> change the name of plugin

src/main/java/com/checkmarx/intellij/tool/window/actions/CancelScanAction.java, src/main/java/com/checkmarx/intellij/tool/window/actions/StartScanAction.java
=> Add try-catch to update scan (AST-65497)

src/main/java/com/checkmarx/intellij/tool/window/actions/CancelScanAction.java, src/main/java/com/checkmarx/intellij/tool/window/actions/CollapseAllAction.java, src/main/java/com/checkmarx/intellij/tool/window/actions/OpenSettingsAction.java, src/main/java/com/checkmarx/intellij/tool/window/actions/StartScanAction.java, src/main/java/com/checkmarx/intellij/tool/window/actions/selection/ResetSelectionAction.java
=> Change deprecated ActionUpdateThread func (AST-65497)

src/main/java/com/checkmarx/intellij/tool/window/actions/CancelScanAction.java, src/main/java/com/checkmarx/intellij/tool/window/actions/CollapseAllAction.java, src/main/java/com/checkmarx/intellij/tool/window/actions/OpenSettingsAction.java, src/main/java/com/checkmarx/intellij/tool/window/actions/StartScanAction.java, src/main/java/com/checkmarx/intellij/tool/window/actions/selection/ResetSelectionAction.java
Reverts Checkmarx/ast-jetbrains-plugin#270
=> Revert "Change deprecated ActionUpdateThread func (AST-65497)"

build.gradle
=> Update Release Version Verification to  IC-2023.2 version

build.gradle
=> Update java-wrapper-version for relase

build.gradle
=> Update JavaWrapper for realse

build.gradle
=> Update Java wrapper to 2.1.3

CODEOWNERS, src/main/java/com/checkmarx/intellij/inspections/AscaInspection.java
> Add actual start index to ASCA problems descriptors
> https://checkmarx.atlassian.net/browse/AST-69534
>
=> Add Start Index For ASCA Problems (AST-69534)

build.gradle
=> update java wrapper

.github/workflows/ci.yml, .github/workflows/test-ui-mac.yml, .github/workflows/test-ui-ubuntu.yml, .github/workflows/test-ui-windows.yml, build.gradle, src/main/java/com/checkmarx/intellij/Constants.java, src/main/java/com/checkmarx/intellij/commands/Project.java, src/main/java/com/checkmarx/intellij/tool/window/actions/StartScanAction.java, src/main/java/com/checkmarx/intellij/tool/window/actions/selection/BranchSelectionGroup.java, src/test/java/com/checkmarx/intellij/BranchSelectionGroupTest.java, src/test/java/com/checkmarx/intellij/StartScanActionTest.java, src/test/java/com/checkmarx/intellij/standard/commands/TestProject.java
=> Create A CxOne Scan From A Local branch (AST-75821)

build.gradle
=> Upgrade java wrapper version (AST-000)

.github/workflows/release.yml
> https://checkmarx.atlassian.net/browse/AST-77702
>
=> Update artifact version (AST-77702)

.github/workflows/release.yml
=> Change condition for stepping in notify (AST-000)

.github/workflows/release.yml, src/main/java/com/checkmarx/intellij/tool/window/actions/StartScanAction.java, src/main/java/com/checkmarx/intellij/tool/window/actions/selection/BranchSelectionGroup.java, src/main/java/com/checkmarx/intellij/tool/window/actions/selection/RootGroup.java, src/test/java/com/checkmarx/intellij/unit/StartScanActionTest.java
> https://checkmarx.atlassian.net/browse/AST-80548
>
=> Add local branch name into dropdown after scan finished (AST-80458)

build.gradle, src/main/java/com/checkmarx/intellij/ASCA/AscaService.java, src/main/java/com/checkmarx/intellij/commands/ASCA.java, src/main/java/com/checkmarx/intellij/commands/Authentication.java, src/main/java/com/checkmarx/intellij/commands/Project.java, src/main/java/com/checkmarx/intellij/commands/Scan.java, src/main/java/com/checkmarx/intellij/commands/TenantSetting.java, src/main/java/com/checkmarx/intellij/commands/Triage.java, src/main/java/com/checkmarx/intellij/commands/results/Results.java, src/main/java/com/checkmarx/intellij/settings/global/CxWrapperFactory.java, src/main/java/com/checkmarx/intellij/settings/global/GlobalSettingsComponent.java, src/main/java/com/checkmarx/intellij/tool/window/actions/StartScanAction.java, src/main/java/com/checkmarx/intellij/tool/window/actions/selection/ScanSelectionGroup.java, src/main/java/com/checkmarx/intellij/tool/window/results/tree/nodes/ResultNode.java, src/test/java/com/checkmarx/intellij/integration/standard/BaseTest.java, src/test/java/com/checkmarx/intellij/unit/commands/ASCATest.java, src/test/java/com/checkmarx/intellij/unit/commands/ProjectTest.java, src/test/java/com/checkmarx/intellij/unit/commands/ScanTest.java, src/test/java/com/checkmarx/intellij/unit/commands/TenantSettingTest.java, src/test/java/com/checkmarx/intellij/unit/commands/TriageTest.java
=> Upgrade Java Wrapper to 2.2.0

src/test/java/com/checkmarx/intellij/ui/TestAsca.java
=> Add check for OK_BTN presence before clicking in TestAsca

src/main/java/com/checkmarx/intellij/tool/window/actions/StartScanAction.java, src/test/java/com/checkmarx/intellij/integration/standard/commands/TestTriage.java
=> Fix UI tests fail in pipeline (AST-93705)

build.gradle, src/main/java/com/checkmarx/intellij/Utils.java, src/main/java/com/checkmarx/intellij/commands/results/Results.java, src/main/java/com/checkmarx/intellij/settings/global/GlobalSettingsSensitiveState.java, src/main/java/com/checkmarx/intellij/tool/window/CxToolWindowPanel.java, src/main/java/com/checkmarx/intellij/tool/window/actions/CancelScanAction.java, src/main/java/com/checkmarx/intellij/tool/window/actions/StartScanAction.java, src/main/java/com/checkmarx/intellij/tool/window/actions/selection/BranchSelectionGroup.java, src/main/java/com/checkmarx/intellij/tool/window/actions/selection/ProjectSelectionGroup.java, src/main/java/com/checkmarx/intellij/tool/window/actions/selection/ScanSelectionGroup.java, src/main/java/com/checkmarx/intellij/tool/window/results/tree/ResultsTreeFactory.java, src/main/java/com/checkmarx/intellij/tool/window/results/tree/nodes/ResultNode.java, src/main/java/com/checkmarx/intellij/util/InputValidator.java, src/test/java/com/checkmarx/intellij/ui/BaseUITest.java
This PR removes usages of deprecated APIs and outdated libraries in the Checkmarx IntelliJ plugin to ensure compatibility with newer IntelliJ Platform SDK versions (2022.2+ through 2025.x).
Specifically:
1. Removed dependency on old org.apache.commons.lang.StringUtils (from Apache Commons Lang 2.x, which JetBrains no longer bundles). Replaced with a local helper method
2. Replaced deprecated Notification constructor with the modern NotificationGroupManager / builder-based notification APIs.
3. Replaced java.net.URL(String) constructor …
=> Remove deprecated code from IntelliJ Plugin (AST-109419)
